baseurl = "https://nerds-of-a-feather.github.io"
DefaultContentLanguage = "en"
title = "Nerds of A Feather"
# Using theme as git submodule
theme = "beautifulhugo"

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    id = "G-NQDNJNYFFC"

[Params]
  homeTitle = "Nerds of a Feather" # Set a different text for the header on the home page
  subtitle = ""
  
  custom_css = ["css/custom.css"]
  mainSections = ["library"]

  logo = "img/avatar-icon.png" # Icon in the sphere.
  favicon = "img/favicon.ico" # Icon in the tab of the browser.

  dateFormat = "January 2, 2006"
  rss = true
  comments = false

  useHLJS = true
  showRelatedPosts = true
  socialShare = false

  katex = false

#  delayDisqus = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "images/test-banner.jpg"
#  desc = "Test Banner"

#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Aalok Varma"
  website = "https://varmaalok22.github.io"
  email = "youremail@domain.com"
  facebook = "username"
  github = "username"
  gitlab = "username"
  bitbucket = "username"
  twitter = "username"
  reddit = "username"
  linkedin = "username"
  xing = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  soundcloud = "username"
  spotify = "username"
  bandcamp = "username"
  itchio = "username"
  vk = "username"
  paypal = "username"
  telegram = "username"
  500px = "username"
  codepen = "username"
  mastodon = "url"
  kaggle = "username"
  weibo = "username"
  slack = "username"
  medium = "username"
  discord = "invite code (https://discord.gg/XXXXXXX)"
  strava = "userid"
  lastfm = "username"
  bluesky = "username"

[[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
